title: The OpenMetrics project â€” Creating a standard for exposing metrics data
baseurl: https://openmetrics.io
languagecode: en
disableKinds: [taxonomy, taxonomyTerm]

params:
  description: |
    An effort to create an open standard for transmitting metrics at scale, with support for both [text representation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) and [Protocol Buffers](https://developers.google.com/protocol-buffers/).
  subdescription: |
    OpenMetrics is **coming soon**. You can track the project's progress in the [OpenMetrics](https://github.com/OpenObservability/OpenMetrics) repository on GitHub or on the [OpenMetrics mailing list](https://groups.google.com/forum/m/#!forum/openmetrics).
  font:
    face: Noto Sans
    sizes: [300, 400, 600, 700]
